export const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESSFULLY = "GET_USER_DETAILS_SUCCESSFULLY";
export const GET_USER_DETAILS_FAILED = "GET_USER_DETAILS_FAILED";